### ISSUE TITLE
Nel controller cambiare metodo statico in metodo d'istanza

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/rubrica-gal#2]
Il controller non deve avere metodi statici ma solod'istanza

**Comment by FedericoRez** [comment]
Ho risolto il ticket aggiungendo alla classe controller la propieta contatore id ...

public class RubricagalController {

    int **_cont_** = 0;
    List<RubricaGalDto> rubrica = new ArrayList<>();

    //Metodo che consente di inserire un contatto nella rubrica
    @RequestMapping("/inserisciContatto")
    public List<RubricaGalDto> inserisciContatto(@RequestBody RubricaGalDto contatto) {
        contatto.setID(**_cont_**);
        this.rubrica.add(contatto);
        **_cont++;_**
        return this.rubrica;
    }
