### ISSUE TITLE
Nel component.ts usare un ogegtto Contatto anche per leggere i campi di input

### ISSUE THREAD

**Issue by luca-lezzerini** [luca-lezzerini/rubrica-gal#3]
Sono state usate variabili distinte:

nomeC: String;
  cognomeC: String;
  telefonoC: String;

Usare istanza di Contatto.

**Comment by FedericoRez** [comment]
Le proprietà dell'istanza di contatto sono state usate nell'app componets e nell'iterfaccia del client al posto dell evariabili distinte

![appComponent_modify](https://user-images.githubusercontent.com/78588276/107275696-63d99b00-6a52-11eb-8a89-fb38c6f8d6c3.png)
![uiHtmlModify](https://user-images.githubusercontent.com/78588276/107275698-64723180-6a52-11eb-9f3f-8415687b1f56.png)

**Comment by luca-lezzerini** [comment]
Mi chiude il ticket se la questione è risolta, per favore?
