### ISSUE TITLE
Errore Git Hub desktop pull classe Contatto e TestMain

### ISSUE THREAD

**Issue by ManuelBava** [luca-lezzerini/rubrica-gal#4]
![Annotazione 2021-02-08 231255](https://user-images.githubusercontent.com/78487457/107288152-45c86680-6a63-11eb-9d5b-5f4defcd7eff.png)

**Comment by luca-lezzerini** [comment]
Ha modificato localmente sul suo PC i file indicati (Contatto e testMain) ma qualcuno, nel frattempo, li ha aggiornati sul repository, quindi la sua versione è vecchia rispetto al repository centrale.
Può fare 3 cose: merge (ma non sa come fare e quindi lo scartiamo), discard (ossia butta via le sue modifiche locali e poi può fare pull), merge simulato (copia i due file modificati altrove, esegue un discard e poi, a mano, verifica cosa sia cambiato e lo riallinea, dopo di che commit e push).

**Comment by ManuelBava** [comment]
Ho risolto professore la ringrazio.
