### ISSUE TITLE
APPLICATION FAILED TO START

### ISSUE THREAD

**Issue by FedericoRez** [luca-lezzerini/rubrica-gal#8]
**Quando eseguo il server la connessione al db avviene con successo, la creazione delle tabelle allinterno del db anche solamente che mi da l'errore indicato qui sopra riguradante l'iniezione dei servizi :( ...**

> --- exec-maven-plugin:3.0.0:exec (default-cli) @ rubricagal ---
> 
>   .   ____          _            __ _ _
>  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
> ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
>  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
>   '  |____| .__|_| |_|_| |_\__, | / / / /
>  =========|_|==============|___/=/_/_/_/
>  :: Spring Boot ::                (v2.4.2)
> 
> 2021-02-14 16:47:48.451  WARN 11212 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'rubricagalController': Unsatisfied dependency expressed through field 'rubricaService'; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'RubricagalService.java.RubricaService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
> 2021-02-14 16:47:48.481 ERROR 11212 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   : 
> 
> ***************************
> APPLICATION FAILED TO START
> ***************************
> 
> Description:
> 
> **Field rubricaService in it.sirfin.rubricagal.controller.RubricagalController required a bean of type 'RubricagalService.java.RubricaService' that could not be found.
> 
> The injection point has the following annotations:
> 	- @org.springframework.beans.factory.annotation.Autowired(required=true)
![Immagine 2021-02-14 165834](https://user-images.githubusercontent.com/78588276/107881690-cb299c00-6ee5-11eb-83a9-fbbeecd28c9a.png)
![Immagine 2021-02-14 165834](https://user-images.githubusercontent.com/78588276/107881694-d2e94080-6ee5-11eb-99bb-80b8fc92a402.png)

**
> 
> 
> Action:
> 
> Consider defining a bean of type 'RubricagalService.java.RubricaService' in your configuration.
> 
> Command execution failed.
> org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
>     at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
>     at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
>     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:982)
>     at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:929)
>     at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:457)
>     at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
>     at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
>     at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
>     at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
>     at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
>     at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
>     at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
>     at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
>     at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
>     at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
>     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
>     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
>     at java.lang.reflect.Method.invoke (Method.java:564)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
>     at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
> ------------------------------------------------------------------------
> BUILD FAILURE
> ------------------------------------------------------------------------
> Total time:  5.556 s
> Finished at: 2021-02-14T16:47:49+01:00
> ------------------------------------------------------------------------
> Failed to execute goal org.codehaus.mojo:exec-maven-plugin:3.0.0:exec (default-cli) on project rubricagal: Command execution failed.: Process exited with an error: 1 (Exit value: 1) -> [Help 1]
> 
> To see the full stack trace of the errors, re-run Maven with the -e switch.
> Re-run Maven using the -X switch to enable full debug logging.
> 
> For more information about the errors and possible solutions, please read the following articles:
> [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
>

**Comment by luca-lezzerini** [comment]
Setviceimpl deve essere annotato @service

**Comment by ManuelBava** [comment]
Professore è già annotato @Service

**Comment by luca-lezzerini** [comment]
Il problema è sul servizio. Conttollate che nellautowired sia scritto bene, che implementi l'interfaccia e che sia annotato. Il problema è li controllate bene. Ora devolliamo e non posso scrivere x un paio d'ore

**Comment by FedericoRez** [comment]
per quanto riguarda le cose descritte da lei sopra è tutto apposto. Può essere che il problema sia l'estensione del package "service" e "serviceImp" ? li abbiamo aggiunti per sbaglio come Service.java e ServiceImp.java invece che .service e serviceImp ...

**Comment by luca-lezzerini** [comment]
Avete messo i file dei servizi nei package sbagliati dovete spostarli sotto it.sirfin.service it.sirfin.service.impl senjo Spring jon li vede

**Comment by luca-lezzerini** [comment]
Afferrateli col mouse e muoveteli nei package giusti e poi avviate il refactoring

**Comment by FedericoRez** [comment]
ottimo, abbiamo risolto. Grazie
